/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerComplaint;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.util.Date.*;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author ADVAIT
 */
public class ComplaintApp extends javax.swing.JFrame {

    String custname,custaddr,custtel,custemail;
    String compCustEmail,comptype, compremark,compStatus;
    final String DRIVER = "com.mysql.jdbc.Driver";
    final String DBURL = "jdbc:mysql://localhost:3306/Complaint";
    final String USERNAME = "root";
    final String PASSWORD = "root";
    
    /**
     * Creates new form ComplaintApp
     */
    public ComplaintApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        custnamelbl = new javax.swing.JLabel();
        custnametxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        custteltxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        custemailtxt = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        custaddrtxt = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        compCustEmailtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comptypeList = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        compRemarktxt = new javax.swing.JTextArea();
        registerCompBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        statusCompid = new javax.swing.JTextField();
        statusList = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        updateStatusBtn = new javax.swing.JButton();
        chkStatusbtn = new javax.swing.JButton();
        chkStatuslbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        custnamelbl.setText("Cutomer Name");

        jLabel1.setText("Address");

        jLabel2.setText("Telephone");

        custteltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custteltxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Email");

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        custaddrtxt.setColumns(20);
        custaddrtxt.setRows(5);
        jScrollPane1.setViewportView(custaddrtxt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custnamelbl)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(custnametxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custteltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custemailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerBtn))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custnamelbl)
                            .addComponent(custnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(109, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(custteltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(custemailtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(registerBtn)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cutomer Registration", jPanel1);

        jLabel4.setText("Customer Email");

        jLabel5.setText("Complaint Type");

        comptypeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer", "Laptop", "Mouse", "Keyboard" }));

        jLabel6.setText("Complaint Remarks");

        compRemarktxt.setColumns(20);
        compRemarktxt.setRows(5);
        jScrollPane2.setViewportView(compRemarktxt);

        registerCompBtn.setText("Register Complaint");
        registerCompBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerCompBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(comptypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compCustEmailtxt)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(registerCompBtn)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(compCustEmailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comptypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registerCompBtn)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Complaint Registration", jPanel2);

        jLabel7.setText("Complaint ID");

        statusList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Resolved" }));

        jLabel8.setText("Status");

        updateStatusBtn.setText("Update Status");
        updateStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStatusBtnActionPerformed(evt);
            }
        });

        chkStatusbtn.setText("Check Status");
        chkStatusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkStatusbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusCompid, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(chkStatusbtn)
                                .addGap(0, 33, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(chkStatuslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(updateStatusBtn)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(statusCompid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkStatusbtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(chkStatuslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(updateStatusBtn)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Complaint Status Management", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStatusBtnActionPerformed
        // TODO add your handling code here:
        compStatus = statusList.getItemAt(statusList.getSelectedIndex());
        int compid = Integer.parseInt(statusCompid.getText());
        int compcustid=0;
        PreparedStatement ps;
        try{

            Class.forName(DRIVER);
            Connection con = DriverManager.getConnection(DBURL,USERNAME,PASSWORD);
            Statement st = con.createStatement();
            st.executeUpdate("Update complain set compstatus ='"+compStatus+"'where compid = '"+compid+"';");

            Statement selectCustomer = con.createStatement();
            ResultSet rs2 = selectCustomer.executeQuery("Select * from complain where compid ='"+compid+"' ;");
            while(rs2.next())
            {
                compcustid = rs2.getInt(5);
            }

            java.util.Date date=new java.util.Date();
            java.sql.Timestamp sqlTime=new java.sql.Timestamp(date.getTime());

            if(compStatus == "Resolved" && compcustid != 0)
            {
                ps = con.prepareStatement("Insert into complaintlog values(?,?,?);");
                ps.setInt(1, compcustid);
                ps.setInt(2, compid);
                ps.setTimestamp(3, sqlTime);

                ps.executeUpdate();

                Statement delrowfromComplain = con.createStatement();
                delrowfromComplain.executeUpdate("Delete from complain where compid ='"+compid+"'and compstatus = 'Resolved'");
            }

            con.close();
            JOptionPane.showMessageDialog(this, "Status Updated Successfully", "Update Success", JOptionPane.INFORMATION_MESSAGE);

        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateStatusBtnActionPerformed

    private void registerCompBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCompBtnActionPerformed
        // TODO add your handling code here:
        compCustEmail = compCustEmailtxt.getText();
        comptype = comptypeList.getItemAt(comptypeList.getSelectedIndex());
        compremark = compRemarktxt.getText();
        compStatus = "Registered";
        int cid=0;
        int complainId=0;
        try{
            Class.forName(DRIVER);
            Connection con = DriverManager.getConnection(DBURL,USERNAME,PASSWORD);

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from customer where custemail = '"+compCustEmail+"';");
            while (rs.next())
            {
                cid = rs.getInt(1);
            }

            if(cid!=0){
                PreparedStatement ps = con.prepareStatement("Insert into complain(comptype,compremark,compstatus,custid) values (?,?,?,?)");
                ps.setString(1, comptype);
                ps.setString(2, compremark);
                ps.setString(3, compStatus);
                ps.setInt(4,cid);

                ps.executeUpdate();

            }
            Statement compidStmt = con.createStatement();
            ResultSet rs1 = compidStmt.executeQuery("select max(compid) from complain");
            while(rs1.next())
            {
                complainId = rs1.getInt(1);
            }
            con.close();

            JOptionPane.showMessageDialog(this, "<html><b>Complaint ID : "+ complainId+"</b><br/><br/>Registered complaint for "+comptype+"</html>", "Success", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Inserted in Complain");

        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_registerCompBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        custname = custnametxt.getText();
        custaddr = custaddrtxt.getText();
        custtel  = custteltxt.getText();
        custemail = custemailtxt.getText();
        try{

            Class.forName(DRIVER);
            Connection con = DriverManager.getConnection(DBURL,USERNAME,PASSWORD);
            PreparedStatement ps = con.prepareStatement("Insert into customer(custname,custaddr,custtel,custemail) values (?,?,?,?);");
            ps.setString(1,custname);
            ps.setString(2,custaddr);
            ps.setString(3,custtel);
            ps.setString(4,custemail);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Registration Successful","Success",JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Inserted Succesfully into Cutomer table");
            con.close();

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void custteltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custteltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custteltxtActionPerformed

    private void chkStatusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkStatusbtnActionPerformed
        // TODO add your handling code here:
        int compid = Integer.parseInt(statusCompid.getText());
        String chkStatus="Resolved";
        try{
            
            Class.forName(DRIVER);
            Connection con = DriverManager.getConnection(DBURL,USERNAME,PASSWORD);
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select compstatus from complain where compid = '"+compid+"';");
            while(rs.next())
            {
                chkStatus = rs.getString(1);
            }
            chkStatuslbl.setText("Current Status: "+chkStatus);
        }catch(Exception e)
        {   
            e.printStackTrace();
        }
    }//GEN-LAST:event_chkStatusbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComplaintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComplaintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComplaintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplaintApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComplaintApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chkStatusbtn;
    private javax.swing.JLabel chkStatuslbl;
    private javax.swing.JTextField compCustEmailtxt;
    private javax.swing.JTextArea compRemarktxt;
    private javax.swing.JComboBox<String> comptypeList;
    private javax.swing.JTextArea custaddrtxt;
    private javax.swing.JTextField custemailtxt;
    private javax.swing.JLabel custnamelbl;
    private javax.swing.JTextField custnametxt;
    private javax.swing.JTextField custteltxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton registerCompBtn;
    private javax.swing.JTextField statusCompid;
    private javax.swing.JComboBox<String> statusList;
    private javax.swing.JButton updateStatusBtn;
    // End of variables declaration//GEN-END:variables
}
